import { existsSync, realpathSync } from "node:fs";
import path from "node:path";
import {
  check,
  cleanupTemp,
  createAuditContext,
  finalize,
  readText,
  runCommand,
  writeJson,
  type AuditContext,
} from "./lib.js";

function sourceCliCommand(ctx: AuditContext, args: string[]): string[] {
  return [
    path.join(ctx.repoRoot, "node_modules", ".bin", "tsx"),
    path.join(ctx.repoRoot, "packages", "cli", "src", "bin.ts"),
    ...args,
  ];
}

function setupFixtureScript(): string {
  return String.raw`
const fs = require("node:fs");
const path = require("node:path");

const [homeDir, projectDir] = process.argv.slice(1);
const settingsPath = path.join(projectDir, ".claude", "settings.local.json");

fs.mkdirSync(path.join(homeDir, ".teamagent", "global"), { recursive: true });
fs.mkdirSync(path.join(homeDir, ".teamagent", "personal"), { recursive: true });
fs.mkdirSync(path.join(projectDir, ".teamagent", "team", "nested"), { recursive: true });
fs.mkdirSync(path.join(projectDir, ".claude"), { recursive: true });

fs.writeFileSync(path.join(homeDir, ".teamagent", "global", "knowledge.jsonl"), '{"id":"global-rule"}\n');
fs.writeFileSync(path.join(homeDir, ".teamagent", "personal", "knowledge.jsonl"), '{"id":"personal-rule"}\n');
fs.writeFileSync(path.join(projectDir, ".teamagent", "team", "nested", "knowledge.jsonl"), '{"id":"team-rule"}\n');

fs.writeFileSync(
  path.join(projectDir, "CLAUDE.md"),
  [
    "# Manual",
    "",
    "User manual rule A",
    "",
    "<!-- TEAMAGENT:START - generated by TeamAgent -->",
    "## TeamAgent generated knowledge",
    "- This block must be removed by uninstall.",
    "<!-- TEAMAGENT:END -->",
    "",
    "## Ops",
    "User manual rule B",
    "",
  ].join("\n"),
);

fs.writeFileSync(
  path.join(path.dirname(settingsPath), "settings.local.json"),
  JSON.stringify(
    {
      permissions: {
        allow: ["Bash(echo user)"],
      },
      hooks: {
        PreToolUse: [
          {
            matcher: "Bash",
            _teamagentTag: "teamagent-pre-tool-use",
            hooks: [{ type: "command", command: "node /tmp/teamagent-pre.cjs", timeout: 30 }],
          },
          {
            matcher: "Write",
            hooks: [{ type: "command", command: "user-pre.sh", timeout: 9 }],
          },
        ],
        PostToolUse: [
          {
            matcher: "Edit",
            _teamagentTag: "teamagent-post-tool-use",
            hooks: [{ type: "command", command: "node /tmp/teamagent-post.cjs", timeout: 30 }],
          },
          {
            matcher: "Read",
            hooks: [{ type: "command", command: "user-post.sh" }],
          },
        ],
        UserPromptSubmit: [
          {
            _teamagentTag: "teamagent-user-prompt-submit",
            hooks: [{ type: "command", command: "node /tmp/teamagent-user-prompt.cjs", timeout: 10 }],
          },
          {
            hooks: [{ type: "command", command: "user-prompt.sh" }],
          },
        ],
        Stop: [
          {
            _teamagentTag: "teamagent-stop",
            hooks: [{ type: "command", command: "node /tmp/teamagent-stop.cjs", timeout: 60 }],
          },
          {
            hooks: [{ type: "command", command: "user-stop.sh" }],
          },
        ],
        Notification: [
          {
            hooks: [{ type: "command", command: "user-notify.sh" }],
          },
        ],
      },
      statusLine: {
        type: "command",
        command: "node /tmp/teamagent-statusline.cjs",
        _teamagentTag: "teamagent-statusline",
      },
      env: {
        USER_SETTING: "keep",
      },
    },
    null,
    2,
  ) + "\n",
);

fs.writeFileSync(
  path.join(path.dirname(homeDir), "CLAUDE.expected.md"),
  [
    "# Manual",
    "",
    "User manual rule A",
    "",
    "## Ops",
    "User manual rule B",
    "",
  ].join("\n"),
);

fs.writeFileSync(
  path.join(path.dirname(homeDir), "settings.expected.json"),
  JSON.stringify(
    {
      permissions: {
        allow: ["Bash(echo user)"],
      },
      hooks: {
        PreToolUse: [
          {
            matcher: "Write",
            hooks: [{ type: "command", command: "user-pre.sh", timeout: 9 }],
          },
        ],
        PostToolUse: [
          {
            matcher: "Read",
            hooks: [{ type: "command", command: "user-post.sh" }],
          },
        ],
        UserPromptSubmit: [
          {
            hooks: [{ type: "command", command: "user-prompt.sh" }],
          },
        ],
        Stop: [
          {
            hooks: [{ type: "command", command: "user-stop.sh" }],
          },
        ],
        Notification: [
          {
            hooks: [{ type: "command", command: "user-notify.sh" }],
          },
        ],
      },
      env: {
        USER_SETTING: "keep",
      },
    },
    null,
    2,
  ) + "\n",
);

console.log(JSON.stringify({ homeDir, projectDir, settingsPath }));
`;
}

function semanticJsonValidatorScript(): string {
  return String.raw`
const fs = require("node:fs");

function fail(message) {
  console.error(message);
  process.exit(1);
}

const settingsPath = process.argv[1];
const settings = JSON.parse(fs.readFileSync(settingsPath, "utf8"));
const serialized = JSON.stringify(settings);

for (const tag of [
  "teamagent-pre-tool-use",
  "teamagent-post-tool-use",
  "teamagent-user-prompt-submit",
  "teamagent-stop",
  "teamagent-statusline",
]) {
  if (serialized.includes(tag)) fail("residual TeamAgent tag: " + tag);
}

const hooks = settings.hooks || {};
const expected = {
  PreToolUse: "user-pre.sh",
  PostToolUse: "user-post.sh",
  UserPromptSubmit: "user-prompt.sh",
  Stop: "user-stop.sh",
  Notification: "user-notify.sh",
};

for (const [hookName, command] of Object.entries(expected)) {
  const entries = hooks[hookName];
  if (!Array.isArray(entries) || entries.length !== 1) {
    fail(hookName + " user hook count mismatch: " + JSON.stringify(entries));
  }
  const actual = entries[0] && entries[0].hooks && entries[0].hooks[0] && entries[0].hooks[0].command;
  if (actual !== command) fail(hookName + " user hook not preserved: " + String(actual));
}

if (settings.statusLine !== undefined) fail("TeamAgent tagged statusLine was not removed");
if (!settings.env || settings.env.USER_SETTING !== "keep") fail("user env config was not preserved");
if (!settings.permissions || !settings.permissions.allow || settings.permissions.allow[0] !== "Bash(echo user)") {
  fail("user permissions config was not preserved");
}

console.log("JSON_ASSERTIONS_PASS");
`;
}

function lines(text: string): string[] {
  return text
    .split(/\r?\n/)
    .map((line) => line.trim())
    .filter((line) => line.length > 0);
}

const ctx = createAuditContext("feature-12", "uninstall-delete-data");
const settingsPath = path.join(ctx.projectDir, ".claude", "settings.local.json");
const expectedClaude = path.join(ctx.tmpDir, "CLAUDE.expected.md");
const expectedSettings = path.join(ctx.tmpDir, "settings.expected.json");
const tsxPath = path.join(ctx.repoRoot, "node_modules", ".bin", "tsx");
const artifacts: Record<string, string> = {};

const tsxExists = existsSync(tsxPath);
let setupExitOk = false;
let beforeFindExitOk = false;
let beforeFiles: string[] = [];
let uninstallExitOk = false;
let afterFindExitOk = false;
let afterTeamagentDirs: string[] = [];
let claudeDiffOk = false;
let settingsDiffOk = false;
let jsonValidatorOk = false;
let cliOutputOk = false;

try {
  if (tsxExists) {
    const setup = runCommand(ctx, "external-fixture-setup", ["node", "-e", setupFixtureScript(), ctx.homeDir, ctx.projectDir], {
      allowFailure: true,
      timeoutMs: 30_000,
    });
    setupExitOk = setup.exitCode === 0;
    artifacts["fixtureSetupStdout"] = setup.stdoutPath;
    artifacts["fixtureSetupStderr"] = setup.stderrPath;
  }

  if (setupExitOk) {
    const beforeFind = runCommand(
      ctx,
      "external-find-before-data",
      [
        "sh",
        "-c",
        'find "$1" "$2" -type f -print | sort',
        "sh",
        path.join(ctx.homeDir, ".teamagent"),
        path.join(ctx.projectDir, ".teamagent"),
      ],
      { allowFailure: true, timeoutMs: 30_000 },
    );
    beforeFindExitOk = beforeFind.exitCode === 0;
    beforeFiles = lines(readText(beforeFind.stdoutPath));
    artifacts["dataBeforeFind"] = beforeFind.stdoutPath;
    artifacts["dataBeforeFindStderr"] = beforeFind.stderrPath;

    const uninstall = runCommand(ctx, "real-cli-uninstall-delete-data", sourceCliCommand(ctx, ["uninstall", "--delete-data"]), {
      cwd: ctx.projectDir,
      env: { HOME: ctx.homeDir },
      allowFailure: true,
      timeoutMs: 120_000,
    });
    uninstallExitOk = uninstall.exitCode === 0;
    artifacts["uninstallStdout"] = uninstall.stdoutPath;
    artifacts["uninstallStderr"] = uninstall.stderrPath;

    const afterFind = runCommand(
      ctx,
      "external-find-after-no-teamagent",
      [
        "sh",
        "-c",
        'out="$(find "$1" "$2" -name .teamagent -print | sort)"; printf "%s" "$out"; test -z "$out"',
        "sh",
        ctx.homeDir,
        ctx.projectDir,
      ],
      { allowFailure: true, timeoutMs: 30_000 },
    );
    afterFindExitOk = afterFind.exitCode === 0;
    afterTeamagentDirs = lines(readText(afterFind.stdoutPath));
    artifacts["dataAfterFind"] = afterFind.stdoutPath;
    artifacts["dataAfterFindStderr"] = afterFind.stderrPath;

    const claudeDiff = runCommand(ctx, "external-diff-claude-md", ["diff", "-u", expectedClaude, path.join(ctx.projectDir, "CLAUDE.md")], {
      allowFailure: true,
      timeoutMs: 30_000,
    });
    claudeDiffOk = claudeDiff.exitCode === 0;
    artifacts["claudeDiffStdout"] = claudeDiff.stdoutPath;
    artifacts["claudeDiffStderr"] = claudeDiff.stderrPath;

    const settingsDiff = runCommand(ctx, "external-diff-settings-json", ["diff", "-u", expectedSettings, settingsPath], {
      allowFailure: true,
      timeoutMs: 30_000,
    });
    settingsDiffOk = settingsDiff.exitCode === 0;
    artifacts["settingsDiffStdout"] = settingsDiff.stdoutPath;
    artifacts["settingsDiffStderr"] = settingsDiff.stderrPath;

    const jsonValidator = runCommand(ctx, "external-node-json-semantic-assertions", ["node", "-e", semanticJsonValidatorScript(), settingsPath], {
      allowFailure: true,
      timeoutMs: 30_000,
    });
    jsonValidatorOk = jsonValidator.exitCode === 0 && readText(jsonValidator.stdoutPath).includes("JSON_ASSERTIONS_PASS");
    artifacts["jsonValidatorStdout"] = jsonValidator.stdoutPath;
    artifacts["jsonValidatorStderr"] = jsonValidator.stderrPath;

    const homeDeleteLine = `已删除: ${path.join(ctx.homeDir, ".teamagent")}`;
    const projectDeleteLine = `已删除: ${path.join(realpathSync(ctx.projectDir), ".teamagent")}`;
    const cliOutput = runCommand(
      ctx,
      "external-grep-cli-output-actions",
      [
        "sh",
        "-c",
        [
          'grep -F "TeamAgent Uninstall" "$1"',
          'grep -F "已移除 hook 注册: " "$1"',
          'grep -F "已从 CLAUDE.md 移除 TEAMAGENT 区块" "$1"',
          `grep -F ${JSON.stringify(homeDeleteLine)} "$1"`,
          `grep -F ${JSON.stringify(projectDeleteLine)} "$1"`,
        ].join("\n"),
        "sh",
        uninstall.stdoutPath,
      ],
      { allowFailure: true, timeoutMs: 30_000 },
    );
    cliOutputOk = cliOutput.exitCode === 0;
    artifacts["cliOutputGrepStdout"] = cliOutput.stdoutPath;
    artifacts["cliOutputGrepStderr"] = cliOutput.stderrPath;
  }

  artifacts["fixturePaths"] = writeJson(ctx, "fixture-paths.json", {
    tmpDir: ctx.tmpDir,
    homeDir: ctx.homeDir,
    projectDir: ctx.projectDir,
    settingsPath,
    expectedClaude,
    expectedSettings,
  });

  const beforeHasProjectData = beforeFiles.some((file) => file.includes(`${path.sep}project${path.sep}.teamagent${path.sep}`));
  const beforeHasHomeData = beforeFiles.some((file) => file.includes(`${path.sep}home${path.sep}.teamagent${path.sep}`));
  const beforeDataOk = beforeFindExitOk && beforeFiles.length >= 3 && beforeHasProjectData && beforeHasHomeData;
  const dataDeletedOk = afterFindExitOk && afterTeamagentDirs.length === 0;
  const allOk =
    tsxExists &&
    setupExitOk &&
    beforeDataOk &&
    uninstallExitOk &&
    dataDeletedOk &&
    claudeDiffOk &&
    settingsDiffOk &&
    jsonValidatorOk &&
    cliOutputOk;

  finalize(ctx, {
    feature: "Feature #12 uninstall --delete-data",
    status: tsxExists ? (allOk ? "passed" : "failed") : "blocked",
    summary: allOk
      ? "通过：runner 在隔离 cwd/HOME 中由外部夹具创建项目级和用户级 TeamAgent 数据、CLAUDE.md 自动区块、TeamAgent tagged hooks/statusLine 与用户配置；随后真实执行 CLI `uninstall --delete-data`，并用 find/diff/Node JSON parser 验证数据删除、自动区块删除、TeamAgent hook/statusLine 删除和用户 hook/config 保留。"
      : tsxExists
        ? "失败：真实 CLI `uninstall --delete-data` 或外部 find/diff/Node JSON parser 验证未全部通过。详见 audit/out 中命令证据。"
        : "阻塞：缺少仓库本地 node_modules/.bin/tsx，无法从真实源码 CLI 入口执行 uninstall。",
    checks: [
      check("tsx executable exists", tsxExists, tsxPath),
      check("external fixture setup succeeded", setupExitOk, `home=${ctx.homeDir}, cwd=${ctx.projectDir}`),
      check(
        "external find saw seeded project and home data",
        beforeDataOk,
        `files=${beforeFiles.length}, homeData=${String(beforeHasHomeData)}, projectData=${String(beforeHasProjectData)}`,
      ),
      check("real CLI uninstall --delete-data exited 0", uninstallExitOk, `cwd=${ctx.projectDir}, HOME=${ctx.homeDir}`),
      check("external find saw no remaining .teamagent dirs", dataDeletedOk, `remaining=${afterTeamagentDirs.join(", ") || "(none)"}`),
      check("external diff confirms CLAUDE.md TeamAgent block removed and user text kept", claudeDiffOk),
      check("external diff confirms settings JSON exact expected shape", settingsDiffOk),
      check("external Node JSON parser confirms TeamAgent tags removed and user hooks kept", jsonValidatorOk),
      check("external grep confirms CLI reported hook, CLAUDE, and both data delete actions", cliOutputOk),
    ],
    artifacts,
  });
} finally {
  cleanupTemp(ctx);
}
