#!/usr/bin/env bash
# bugreport-collect — emit a markdown skeleton ready to paste into
#   https://github.com/libz-renlab-ai/TeamBrain/issues/new
#
# Sections produced (matching CLAUDE.md / docs/BUGREPORT.md contract):
#   1. System info   — populated automatically
#   2. How-to-reproduce-the-bugs   — a placeholder table you must edit
#   3. Raw logs in great detail   — last probe + last verify + tmux scrollback
#                                   of the active dogfood session, untruncated
#
# Token-shaped strings (sk-…, bearer …, API keys) are redacted to [redacted]
# via a simple sed before printing. Other values stay as-is on purpose —
# triagers usually need paths and hostnames.
#
# Usage:
#   bash scripts/bugreport-collect.sh > /tmp/teambrain-bug-report.md
#   # then review, edit Section 2, and paste into a GitHub issue.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

# Collect helper — wraps a command and prints its output in a fenced block.
# Errors are captured (not fatal). Token-shaped strings redacted.
TOKEN_RE='s/sk-[A-Za-z0-9_-]{20,}/[redacted]/g; s/Bearer [A-Za-z0-9._-]{20,}/Bearer [redacted]/g'
fence_cmd () {
  local label="$1"; shift
  echo
  echo "**$label**"
  echo
  echo '```'
  ( "$@" 2>&1 ) | sed -E -e "$TOKEN_RE" || true
  echo '```'
}

cat <<HEADER
# TeamBrain bug report

> Generated by \`bash scripts/bugreport-collect.sh\` on $(date -u +'%Y-%m-%dT%H:%M:%SZ').
> Edit Section 2 (How-to-reproduce-the-bugs) before posting; everything
> else is auto-collected. Posting target:
> https://github.com/libz-renlab-ai/TeamBrain/issues/new

## 1. System info
HEADER

fence_cmd "uname -a" uname -a
fence_cmd "sw_vers (macOS only)" sw_vers
fence_cmd "shell" sh -c 'echo "zsh: $(zsh --version 2>/dev/null || echo not-installed)"; echo "bash: $(bash --version | head -1 2>/dev/null || echo not-installed)"'
fence_cmd "tmux -V" tmux -V
fence_cmd "node / npm" sh -c 'node --version 2>&1 || echo "node not installed"; npm --version 2>&1 || echo "npm not installed"'
fence_cmd "git --version" git --version
fence_cmd "docker --version" sh -c 'docker --version 2>&1 || echo "docker not installed"'

cat <<EOM

**claudefast environment (token redacted)**

\`\`\`
ANTHROPIC_MODEL:        ${ANTHROPIC_MODEL:-unset}
ANTHROPIC_BASE_URL:     ${ANTHROPIC_BASE_URL:-unset}
CLAUDE_CONFIG_DIR:      ${CLAUDE_CONFIG_DIR:-unset}
CODEX_HOME:             ${CODEX_HOME:-unset}
HOME:                   ${HOME:-unset}
CLAUDE_PROJECT_DIR:     ${CLAUDE_PROJECT_DIR:-unset}
PWD:                    $PWD
ANTHROPIC_API_KEY:      [redacted]
\`\`\`
EOM

fence_cmd "git status / branch / SHA" sh -c '
  echo "branch: $(git rev-parse --abbrev-ref HEAD)"
  echo "SHA:    $(git rev-parse --short HEAD)"
  echo "uncommitted entries: $(git status --porcelain | wc -l | tr -d \" \")"
  echo "remote:"
  git remote -v
'

fence_cmd "git log -5 (recent commits)" git log --oneline -5

fence_cmd "git worktree list" git worktree list

fence_cmd "active dogfood session (if any)" sh -c '
  if [ -f .dogfood/active-session ]; then
    SESSION=$(cat .dogfood/active-session)
    SANDBOX=$(cat .dogfood/active-sandbox 2>/dev/null || echo "(none)")
    echo "session: $SESSION"
    echo "sandbox: $SANDBOX"
    if tmux has-session -t "$SESSION" 2>/dev/null; then
      echo "panes:"
      tmux list-panes -t "$SESSION" -F "  #{pane_id}  #{pane_current_command}  cwd=#{pane_current_path}"
    else
      echo "(session DEAD)"
    fi
  else
    echo "(no active dogfood session)"
  fi
'

cat <<'SECTION2'

## 2. How-to-reproduce-the-bugs

**FILL THIS IN** — auto-collection cannot guess your scenario. Provide the minimal
sequence of commands, the expected behavior, and what actually happened.

| Step | Command | Expected | Actual |
|------|---------|----------|--------|
| 1    | `…`     | …        | …      |
| 2    | `…`     | …        | …      |
| 3    | `…`     | …        | …      |

**Hooks / skills / permission gates triggered (if relevant):**
- (e.g. Fact-Forcing Gate fired before bash, laziness-self-report blocked Stop, …)

**`bash scripts/dogfood-review.sh` snapshot** (if dogfood-related):
SECTION2
fence_cmd "dogfood-review output" sh -c '
  if [ -x scripts/dogfood-review.sh ]; then
    bash scripts/dogfood-review.sh 2>&1 || true
  else
    echo "(scripts/dogfood-review.sh not present)"
  fi
'

cat <<'SECTION3'

## 3. Raw logs in great detail

> Untruncated logs go below. Tokens redacted; everything else as-is.
SECTION3

# Last dogfood probe artifacts (paste full content of each jsonl)
LAST_PROBE="$(find .dogfood -maxdepth 1 -type d -name 'probe-*' 2>/dev/null | sort | tail -1)"
if [[ -n "$LAST_PROBE" ]]; then
  echo
  echo "### Last dogfood-probe artifacts (\`$LAST_PROBE\`)"
  for f in "$LAST_PROBE"/*.jsonl; do
    [[ -f "$f" ]] || continue
    fence_cmd "$f" cat "$f"
  done
fi

# Last canned-answer verify captures
for capture in docs/dogfood/.last-verify.out docs/bugreport/.last-verify.out; do
  if [[ -f "$capture" ]]; then
    fence_cmd "$capture" cat "$capture"
  fi
done

# tmux scrollback for the active dogfood session (if any)
if [[ -f .dogfood/active-session ]]; then
  SESSION="$(cat .dogfood/active-session)"
  if tmux has-session -t "$SESSION" 2>/dev/null; then
    echo
    echo "### tmux scrollback (last 3000 lines per pane in \`$SESSION\`)"
    while IFS= read -r pane; do
      [[ -n "$pane" ]] || continue
      fence_cmd "pane $pane" tmux capture-pane -t "$pane" -p -S -3000
    done < <(tmux list-panes -t "$SESSION" -F '#{pane_id}')
  fi
fi

# Recent FASTPROBE artifacts (last run only, to keep size sane)
LAST_FASTPROBE="$(find .fastprobe -maxdepth 1 -type d 2>/dev/null | sort | tail -1)"
if [[ -n "$LAST_FASTPROBE" && -d "$LAST_FASTPROBE" ]]; then
  echo
  echo "### Last FASTPROBE run (\`$LAST_FASTPROBE\`)"
  for f in "$LAST_FASTPROBE"/*.txt "$LAST_FASTPROBE"/*.log "$LAST_FASTPROBE"/*.jsonl; do
    [[ -f "$f" ]] || continue
    fence_cmd "$f" cat "$f"
  done
fi

cat <<FOOTER

---

> Reporter checklist before submitting:
> - [ ] Section 2 filled in with concrete repro
> - [ ] No \`sk-\` / \`Bearer …\` strings in the body (search before posting)
> - [ ] Tagged with the active \`DOGFOOD_TIER\` if the bug is sandbox-related
> - [ ] Linked to any related issue / PR if known

Post at: https://github.com/libz-renlab-ai/TeamBrain/issues/new
FOOTER
