/**
 * Compose the `hookSpecificOutput.additionalContext` block that gets injected
 * into the user's own Claude Code window when a daily-summary trigger fires.
 *
 * The block contains:
 *   1. A short meta-instruction telling Claude what to do.
 *   2. A per-project enumeration with session/turn counts + first/last user
 *      excerpts + tools used (the LLM-free aggregate from aggregator.ts).
 *
 * Claude then writes the final one-line-per-project summary text in chat.
 * TeamAgent itself never calls an LLM (grill §2).
 *
 * The same module also produces the archive markdown body for
 * `${TEAMAGENT_HOME}/daily/<YYYY-MM-DD>.md` (grill §2 输出渠道 (b)).
 */

import type { ProjectDigest } from "./aggregator.js";

export interface RewriterInput {
  /** ISO local date used for "today" window (YYYY-MM-DD). */
  readonly date: string;
  /** Project digests already aggregated. */
  readonly digests: readonly ProjectDigest[];
  /** Whether the matcher fired through the LLM intent-check seam. Informational. */
  readonly matcherReason?: string;
}

const META_INSTRUCTION_HEADER =
  "TeamAgent daily-summary trigger fired. Below is the LLM-free aggregate of the operator's Claude Code activity for today. Please respond with a one-line summary per project, in 中文, first-person voice (例如 \"修了…\" / \"调了…\"). Do not re-list the raw counts; paraphrase what the operator likely accomplished.";

const ZERO_ACTIVITY_BODY =
  "TeamAgent daily-summary trigger fired, but no Claude Code session activity is recorded for the operator today. Please respond briefly in 中文 acknowledging \"今日无 Claude 活动\".";

function formatDigest(d: ProjectDigest): string {
  const lines: string[] = [];
  lines.push(`### ${d.displayName}  (${d.canonicalCwd})`);
  lines.push(
    `- sessions: ${d.sessionCount}` +
      (d.hadWorktreeSession ? " (含 worktree)" : ""),
  );
  lines.push(`- user turns: ${d.userTurnCount}`);
  lines.push(`- assistant chars: ${d.assistantCharCount}`);
  if (d.toolsUsed.length > 0) {
    lines.push(`- tools: ${d.toolsUsed.join(", ")}`);
  }
  if (d.firstUserExcerpt) {
    lines.push(`- first user turn: ${d.firstUserExcerpt}`);
  }
  if (d.lastUserExcerpt && d.lastUserExcerpt !== d.firstUserExcerpt) {
    lines.push(`- last user turn: ${d.lastUserExcerpt}`);
  }
  return lines.join("\n");
}

export function composeAdditionalContext(input: RewriterInput): string {
  if (input.digests.length === 0) {
    return [
      `# TeamAgent daily summary (${input.date})`,
      "",
      ZERO_ACTIVITY_BODY,
    ].join("\n");
  }
  const sections = input.digests.map(formatDigest).join("\n\n");
  return [
    `# TeamAgent daily summary (${input.date})`,
    "",
    META_INSTRUCTION_HEADER,
    "",
    sections,
  ].join("\n");
}

export function composeArchiveMarkdown(input: RewriterInput): string {
  const headerLines = [
    `# Daily activity — ${input.date}`,
    "",
    `_Generated by TeamAgent daily-summary hook (issue #371). LLM-free aggregation of \`~/.claude/projects/\` session logs._`,
    "",
  ];
  if (input.matcherReason) {
    headerLines.push(`_Triggered by: ${input.matcherReason}_`, "");
  }
  if (input.digests.length === 0) {
    headerLines.push("_(no Claude Code activity recorded for today)_");
    headerLines.push("");
    return headerLines.join("\n");
  }
  const sections = input.digests.map(formatDigest).join("\n\n");
  return [...headerLines, sections, ""].join("\n");
}
